return {
    map = {
        [[#X#################################################]],
        [[#                ##               ###             #]],
        [[#                ##               ###             #]],
        [[#                ##               ###             #]],
        [[#                ##               ###             #]],
        [[#                ##               ###             #]],
        [[#                ##               ###             #]],
        [[#                ##               ###             #]],
        [[#                ##               ###             #]],
        [[#                ##               ###             #]],
        [[#                ##               ###             #]],
        [[#                ##               ###             #]],
        [[#                ##               ###             #]],
        [[#                ##               ###             #]],
        [[#                ##               ###             #]],
        [[#                ##               ###             #]],
        [[#                ##             8 ###             #]],
        [[#                ##             # ###             #]],
        [[#                ##     W  6  W## ###             #]],
        [[#                ## 5 ######  ### ###             #]],
        [[#                ##---######--### ###             #]],
        [[#                ##   ######  ### ###             #]],
        [[#                ##   ######  ### ###             #]],
        [[#                ##---######--### ###             #]],
        [[#             3  ##   ######  ### ###  ##         #]],
        [[#             #--##   ######  ### ###  ##         #]],
        [[#            ##  ##---######--### ###  ##         #]],
        [[# S         ###       ######  ### ###  ##         #]],
        [[# 1      2 ####     4 ######  ###     7##         #]],
        [[###################################################]],
    },
    symbols = {
        S = { type = "spawn" },
        R = { type = "enemy", key = "ratto" },
        W = { type = "enemy", key = "worm" },
        G = { type = "enemy", key = "spike_slug" },
        ["1"] = { type = "sign", text = "{move_left}/{move_right} to move!" },
        ["2"] = { type = "sign", text = "{jump} to Jump!" },
        ["3"] = { type = "sign", text = "{move_down} + {jump} to drop!" },
        ["4"] = { type = "sign", text = "Double jump to jump higher!" },
        ["5"] = { type = "sign", text = "{attack} to attack!" },
        ["6"] = { type = "sign", text = "{throw} to throw!" },
        ["7"] = { type = "sign", text = "Jump off walls to climb up!" },
        ["8"] = { type = "sign", text = "Move and hold against wall to slide slowly!" },
    }
}